# Generated by Django 4.0.5 on 2024-09-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default2.jpg', upload_to='user_profile_pics'),
        ),
    ]
