# Generated by Django 4.0.5 on 2024-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], default='Solo', max_length=100),
        ),
    ]
