# Generated by Django 4.0.5 on 2024-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deliver_to',
            field=models.CharField(default='10 obe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='pick_up',
            field=models.CharField(default='42 jimoh', max_length=255),
            preserve_default=False,
        ),
    ]
