# Generated by Django 4.0.5 on 2024-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_deliver_to_task_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], max_length=100),
        ),
    ]
