# Generated by Django 4.0.5 on 2024-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='price',
            field=models.BigIntegerField(default=1500),
            preserve_default=False,
        ),
    ]
